[book]
authors = ["Amaan Khan", "akhan4u"]
language = "en"
multilingual = false
src = "src"
title = "Linux Essentials Training"

[output.html]
theme = "my-theme"
default-theme = "ayu"
preferred-dark-theme = "navy"
